config/routes.rb
G3k::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :carts  do
    resources :line_items do
      collection do
        put :add_product
        delete :destroy_product
      end
    end
  end

  get "/katalog" => "katalog#katalog", :as => :katalog
  get '/katalog/:category_name', to:'katalog#show', as:'category'
  get '/katalog/product/:id' => 'katalog#show_product', :as => :product

  post "/order", to: 'application#order', as: :call_orders

  get "/about_us" => "about_us#about_us", :as => :about
  get "/actsii" => "actii#actsii", :as => :actsii
  get "/publications" => "publications#publications", :as => :publications
  get "/contacts" => "contacts#contacts", :as => :contacts
  get '/publications/articles' => 'article#index', :as => :articles
  get '/publications/articles/:id' => 'article#item', :as => :article_item

  get '/dostavka_po_vsi_ukraini' => 'dostavka_po_vsi_ukraini#delivery_all_over_Ukraine', :as => :dostavka
  get '/pracjujemo_z' => 'pracjujemo_z#working_with', :as => :pracjujemo
  get '/bezproblemne_povernennja' => 'bezproblemne_povernennja#smooth_return', :as => :smooth_return
  get '/garantia_jakosti' => 'garantia_jakosti#quality_assurance', :as => :quality_assurance

  resources "contacts", only: [:new, :create]

  resources "order_products", only: [:new, :create]

  post '/buy_product' => 'home#buy_product', as: :buy_product
  post '/call_order' => 'home#call_order', as: :call_order
  post '/contact_us' => 'home#contact_us', as: :contact_us
  post '/delete_product' => 'line_items#destroy_product', as: :delete_product

  post '/del_all' => 'line_items#del_all', as: :del_all

  

  get 'aae95aece941.html', to: 'yandex_mail#confirm'
  root :to =>'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @title = "G3K - ІГРИ НОВОГО ПОКОЛІННЯ"
    @articles = Article.order('updated_at desc').limit(4)
    @product = Product.order('updated_at desc').limit(4)
    @banner = Banner.order('updated_at asc')
    @bestsellers = Product.where(bestseller: 't')

  end

  def buy_product
    BuyProduct.product_buy(params[:buy_product]).deliver
  end

  def contact_us
    ContactUs.contacts(params[:contact_us]).deliver
  end
  def call_order
    CallOrder.call_order(params[:call_order]).deliver
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.slim
.main_banner#wrap-for-main-banner
  #bxslider
    ul.slides-container.bx-slider
      - if @banner
        -@banner.each do |b|
          li
            img src=b.main_image.url(:large)
            .image-layer1
              img src=b.layer1_image.url
            .container
              p = raw b.description
            .image-layer2
              img src=b.layer2_image.url
.content_menu_wrapper
  .content_menu
    nav
      li.dost_po_Ukraini
        img src="assets/g3k-icon-1-1.svg"
        .link-menu-wrapper
          /= link_to 'Доставка<br/> по всій Україні!'.html_safe, dostavka_path
          = link_to 'Доставка<br/> по всій Україні!'.html_safe, ''
      li.prac_z_2009
        img src="assets/g3k-icon-2-1.svg"
        .link-menu-wrapper
          /= link_to 'Працюємо з 2009 року!', pracjujemo_path
          = link_to 'Працюємо з 2009 року!', ''
      li.bezproble_povernennia
        img src="assets/g3k-icon-3-1.svg"
        .link-menu-wrapper
          /= link_to 'Безпроблемне повернення!', smooth_return_path
          = link_to 'Безпроблемне повернення!', ''
      li.garantia_jakosti
        img src="assets/g3k-icon-4-1.svg"
        .link-menu-wrapper
          /= link_to 'Гарантія якості!', quality_assurance_path
          = link_to 'Гарантія якості!', ''
      .clear
    .clear
.bestsellers
  .title_wrapper
    .title
      | ХІТИ ПРОДАЖУ
  .bestsellers_content_wrapper
    .bestsellers_content
      ul#bestseller-items
        -if @bestsellers
          - @bestsellers.each do |product|
            li.item
              .image
                a href=product_path(product.product_url)
                  img src=product.image
                  .price_wrapper
                    .price_text
                      = product.price
                      |.
                      sup
                        |00
              .content_item
                h2
                  a href=(product_path(product.product_url)) = truncate  product.name, length: 70, omission: '...'
                p
                  = truncate product.short_description, length: 140, omission: '...'
                .add-too-cart
                  .form-actions#main-carousel-action-button
                    img.button_hover_icon src="/assets/g3k-button-arrow-1.png"
                    = button_to 'Замовити!',add_product_cart_line_items_path(session[:cart], :product_id => product.id), :method => :put
                  .link-too-info
                    a#linkToTermsOfDeliveryAndPayment href="#termsOfDeliveryAndPayment"
                      |Умови доставки та оплати

.novelty
  .title_wrapper
    .title
      | НОВИНКИ
  .novelty_content#ib-container2
    ul
      - @product.each do |product|
        li.item
          .image
            a href=product_path(product.product_url)
              img src=product.image
            .price_wrapper
              .price_text
                = product.price
                |.
                sup
                  |00
          .content_item
            h2
              a href=(product_path(product.product_url)) = truncate  product.name, length: 70, omission: '...'
            p
              = truncate product.short_description, length: 105, omission: '...'
            .add-too-cart
              .form-actions
                img.button_hover_icon src="/assets/g3k-button-arrow-1.png"
                = button_to 'Замовити!',add_product_cart_line_items_path(session[:cart], :product_id => product.id), :method => :put

    .clear
.announcements_and_articles
  .title_wrapper
    .title
      | АНОНСИ ТА СТАТТІ
  .articles_content
    - @articles.each do |article|
      .item-news
        .image
          a href=(articles_path+'/'+article.url)
            img src=article.image
        .content
          h2
            a href=(articles_path+'/'+article.url) = truncate  article.title, length: 70, omission: '...'
          span = article.created_at.strftime("%d. %m. %Y")
          p = truncate_html article.article_short_description, length: 230, omission: '...'

.clear